version: "3.9"
services:
  arangodb:
    image: arangodb:latest
    restart: always
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    networks:
      - stix2arango
  postgresql:
    image: postgres:11-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=stix2arango
    networks:
      - stix2arango
networks:
  stix2arango:
    driver: bridge